### ISSUE TITLE
expireSeconds useless in case of page refresh

### ISSUE THREAD

**Issue by stilllife00** [kamranahmedse/redux-persist-expire#1]
`redux-persist` fires at initial action `persist/PERSIST` at page refresh.
This causes the `persistedAtKey` to update to the page refresh time and so `expireSeconds` loses of meaning because it would work only if the user stares at the page for X seconds.

Is this a bug, the desired behavior or am I missing something?

**Comment by kamranahmedse** [comment]
Fixed, thanks for reporting 👍

**Comment by stilllife00** [comment]
I am not sure why but I can still reproduce. The `persistedAt` time get reset at every page refresh to the expiration never happens.
